"Effektavgiften baseras på dina tre högsta effektuttag under en månad – minimera därför varje enskild topp.",
"Undvik att köra flera tunga laster (tvätt, disk, spis) samtidigt för att sprida ut topparna.",
"Schemalägg tunga laster till olika dagar eller mellantider (t.ex. 10–15 eller 20–23) med timers eller smartplugs.",
"Välj korta och energieffektiva program på dina vitvaror för att hålla effektuttagen låga.",
"Logga in på Mitt Göteborg Energi och övervaka dina månadstoppar – sätt upp notiser för att undvika nya topp.",
"Sänk inomhustemperaturen 1-2 °C när du riskerar toppeffekter och använd smart termostat med veckoprogram.",
"Koppla ur standby-apparater och dra nytta av av-/på-grenuttag för att eliminera dolda laster.",
"Se över isolering och täta fönster/dörrar så att värmesystemet arbetar jämnare utan onödiga effekttoppar.",
"https://www.goteborgenergi.se/privat/elnat/elnatsavgiften#effekt",